
language: node_js

node_js:
  - "node"
  
before_install:
  - npm cache clean -f
  - npm install -g n
  - n stable

install:
  - cd angular
  - npm install
  - cd ../node
  - npm install
  - cd ..

script:
  - cd angular
  - npm test
  - cd ../node
  - npm test --harmony
  - cd ..
