
language: node_js

node_js:
  - "node"

install:
  - cd angular
  - npm install
  - cd ../node
  - npm install
  - cd ..

script:
  - cd angular
  - npm test
  - cd ../node
  - npm test --harmony
  - cd ..

notifications:
  email:
    on_success: never
    on_failure: never
