apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: financeapp-data-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: financeapp-data-service
    spec:
      containers:
      - name: financeapp-data-service
        image: "mattcopas/financeapp-data-service:0.0.1"
        env:
        - name: DB_HOST
          value: "${pg_host}"
        - name: DB_PORT
          value: "30060"
        - name: DB_NAME
          value: financedataservicedb
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: password
        - name: allowedOrigin
          value: "http://localhost:3000"
        ports:
        - containerPort: 8081
