apiVersion: v1
kind: Service
metadata:
  name: financeapp-data-service
spec:
  type: NodePort
  selector:
    app: financeapp-data-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081
